modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="forbidden_brews"
version="0.1.0"
displayName="Forbidden Brews"
authors="Magersers"
description='''Chaos Brewing Stand and original animated potion art. Transformation effects are in development.'''
[[dependencies.forbidden_brews]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.forbidden_brews]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
