modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="forbidden_brews"
version="0.2.1"
displayName="Forbidden Brews"
authors="Magersers"
description='''Chaos brewing, Fortune, Looting, Homeward potions and renewable Netherite Wart.'''
[[dependencies.forbidden_brews]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.forbidden_brews]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
