modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="forbidden_brews"
version="0.7.2"
displayName="Forbidden Brews"
authors="Magersers"
description='''Chaos brewing, sixteen potion families and renewable Netherite Wart.'''
[[dependencies.forbidden_brews]]
modId="neoforge"
type="required"
versionRange="[21.1.252,)"
ordering="NONE"
side="BOTH"
[[dependencies.forbidden_brews]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
[[mixins]]
config="forbidden_brews.mixins.json"
